# Generated by Django 3.1.1 on 2020-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ID', models.IntegerField(unique=True)),
                ('NOMBRE', models.CharField(max_length=25)),
                ('AP_PATERNO', models.CharField(max_length=25)),
                ('AP_MATERNO', models.CharField(max_length=25)),
                ('TELEFONO', models.CharField(max_length=20)),
                ('DEPARTAMENTO', models.CharField(max_length=264)),
            ],
        ),
    ]
